# import Libraries

In [1]:
from datetime import datetime as dt
import pandas as pd
import time
import warnings

In [2]:
# Set pandas option to display all columns
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

# Ignore warming to maintain clean output
warnings.filterwarnings('ignore')

# now lets extract the data set

In [3]:
# url link from - https://www.redfin.com/news/data-center/
url_by_city = 'https://redfin-public-data.s3.us-west-2.amazonaws.com/redfin_market_tracker/city_market_tracker.tsv000.gz'

def extract_data(url):
    df = pd.read_csv(url, compression='gzip', sep='\t')
    return df

df = extract_data(url_by_city)

In [4]:
df.head(20)

,period_begin,period_end,period_duration,region_type,region_type_id,table_id,is_seasonally_adjusted,region,city,state,state_code,property_type,property_type_id,median_sale_price,median_sale_price_mom,median_sale_price_yoy,median_list_price,median_list_price_mom,median_list_price_yoy,median_ppsf,median_ppsf_mom,median_ppsf_yoy,median_list_ppsf,median_list_ppsf_mom,median_list_ppsf_yoy,homes_sold,homes_sold_mom,homes_sold_yoy,pending_sales,pending_sales_mom,pending_sales_yoy,new_listings,new_listings_mom,new_listings_yoy,inventory,inventory_mom,inventory_yoy,months_of_supply,months_of_supply_mom,months_of_supply_yoy,median_dom,median_dom_mom,median_dom_yoy,avg_sale_to_list,avg_sale_to_list_mom,avg_sale_to_list_yoy,sold_above_list,sold_above_list_mom,sold_above_list_yoy,price_drops,price_drops_mom,price_drops_yoy,off_market_in_two_weeks,off_market_in_two_weeks_mom,off_market_in_two_weeks_yoy,parent_metro_region,parent_metro_region_metro_code,last_updated
0,2023-09-01,2023-09-30,30,place,6,10126,f,"Lazy Lake, FL",Lazy Lake,Florida,FL,All Residential,-1,1600000.0,NaN,NaN,NaN,NaN,NaN,509.067770,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,171.0,NaN,NaN,0.891365,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Fort Lauderdale, FL",22744,2024-01-14 14:20:58
1,2019-09-01,2019-09-30,30,place,6,26318,f,"West Little River, FL",West Little River,Florida,FL,Single Family Residential,6,216000.0,-0.114754,-0.028995,264900.0,0.038824,0.166960,208.688245,0.146684,0.213632,207.384378,0.087970,0.291357,27.0,-0.100000,0.227273,20.0,-0.130435,-0.130435,25.0,-0.218750,-0.137931,62.0,-0.031250,-0.114286,2.3,0.2,-0.9,44.0,-4.0,-9.0,0.964801,-0.002972,-0.003140,0.185185,-0.148148,-0.087542,0.129032,-0.042843,-0.185253,0.300000,-0.047826,-0.091304,"Miami, FL",33124,2024-01-14 14:20:58
2,2021-12-01,2021-12-31,30,place,6,19849,f,"Sun Valley, ID",Sun Valley,Idaho,ID,All Residential,-1,905000.0,-0.158140,0.022599,549500.0,-0.392818,-0.427604,743.391431,-0.044783,0.535594,753.228121,0.164601,0.263525,14.0,0.555556,0.000000,10.0,0.666667,0.111111,7.0,-0.125000,0.166667,27.0,-0.250000,-0.068966,1.9,-2.1,-0.2,69.0,0.0,24.0,NaN,NaN,NaN,0.000000,0.000000,0.000000,NaN,NaN,NaN,0.100000,0.100000,0.100000,"Hailey, ID",25200,2024-01-14 14:20:58
3,2022-11-01,2022-11-30,30,place,6,17859,f,"South Fulton, TN",South Fulton,Tennessee,TN,Single Family Residential,6,117500.0,-0.533730,-0.347222,136500.0,1.486339,-0.237430,55.025320,-0.546041,-0.472402,72.327265,0.538766,-0.324328,2.0,1.000000,0.000000,3.0,2.000000,0.500000,2.0,-0.333333,-0.333333,7.0,-0.125000,0.000000,3.5,-4.5,0.0,52.0,-14.0,1.0,0.856925,-0.151479,-0.162217,0.000000,-1.000000,-1.000000,NaN,NaN,NaN,0.333333,0.333333,0.333333,"Union City, TN",46460,2024-01-14 14:20:58
4,2014-09-01,2014-09-30,30,place,6,26490,f,"Waggaman, LA",Waggaman,Louisiana,LA,All Residential,-1,50000.0,-0.166667,0.214388,55000.0,-0.147287,-0.592593,37.936267,-0.396468,0.026680,46.230441,0.198293,-0.533575,7.0,-0.363636,0.750000,2.0,-0.333333,0.000000,7.0,-0.363636,0.000000,47.0,0.068182,-0.096154,6.7,2.7,-6.3,651.0,445.0,527.0,0.984588,0.051378,-0.121074,0.142857,0.142857,-0.857143,NaN,NaN,NaN,0.000000,0.000000,0.000000,"New Orleans, LA",35380,2024-01-14 14:20:58
5,2013-11-01,2013-11-30,30,place,6,3931,f,"Collegeville, PA",Collegeville,Pennsylvania,PA,Condo/Co-op,3,195000.0,NaN,NaN,NaN,NaN,NaN,106.790800,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,6.0,NaN,NaN,6.0,NaN,NaN,43.0,NaN,NaN,0.951220,NaN,NaN,0.000000,NaN,NaN,0.166667,NaN,NaN,0.000000,NaN,NaN,"Montgomery County, PA",33874,2024-01-14 14:20:58
6,2013-01-01,2013-01-31,30,place,6,23508,f,"Hurley, NY",Hurley,New York,NY,All Residential,-1,183500.0,-0.356140,-0.375850,166450.0,0.734758,-0.056941,132.793227,0.003171,0.445368,102.674183,0.102482,-0.392332,2.0,-0.333333,1.000000,1.0,NaN,NaN,4.0,1.000000,1.000000,40.0,-0.024390,0.739130,20.0,6.3,-3.0,164.0,45.0,-459.0,0.997421,0.041701,0.017094,0.500000,0.500000,0.500000,NaN,NaN,NaN,0.000000,NaN,NaN,"Kingston, NY",28740,2024-01-14 14:20:58
7,2017-11-01,2017-11-30,30,place,6,34777,f,"Six Mile Run, NJ",Six Mile Run,New Jersey,NJ,Single Family Residential,6,450000.0,-0.054622,0.730769,384950.0,0.604627,0.212846,192.967410,0.131875,0.152477,178.737907,0.165261,0.009222,1.0,-0.750000,-0.500000,NaN,NaN,NaN,2.0,0.000000,-0.500000,9.0,0.000000,-0.181818,9.0,6.7,3.5,20.0,-151.0,-4.0,1.002227,0.008556,0.018156,1.000000,0.500000,0.500000,NaN,NaN,NaN,NaN,NaN,NaN,"New Brunswick, NJ",35154,2024-01-14 14:20:58
8,2014-02-01,2014-02-28,30,place,6,20540,f,"Westernport, MD",Westernport,Maryland,MD,Single Family Residential,6,50000.0,0.052632,0.369863,34900.0,0.000000,NaN,39.304671,-0.143223,-0.095454,13.569207,-0.339650,NaN,2.0,0.000000,1.000000,1.0,0.000000,NaN,1.0,0.000000,NaN,15.0,0.000000,0.153846,7.5,0.0,-5.5,40.0,-1.0,-130.0,0.862599,-0.196919,0.051488,0.000000,-0.500000,0.000000,0.133333,0.000000,-0.020513,1.000000,1.000000,NaN,"Cumberland, MD",19060,2024-01-14 14:20:58
9,2017-09-01,2017-09-30,30,place,6,12291,f,"Neptune Beach, FL",Neptune Beach,Florida,FL,Single Family Residential,6,495000.0,-0.143969,-0.034146,394950.0,-0.300973,-0.010150,155.562539,-0.448351,-0.354707,234.142875,-0.115055,0.222226,1.0,-0.833333,-0.750000,1.0,-0.750000,-0.750000,5.0,-0.444444,-0.545455,23.0,0.150000,-0.258065,23.0,19.7,15.2,212.0,129.0,183.0,0.960883,0.013804,-0.031390,0.000000,-0.166667,-0.250000,0.260870,0.160870,0.196353,0.000000,-0.500000,-0.250000,"Jacksonville, FL",27260,2024-01-14 14:20:58
10,2013-12-01,2013-12-31,30,place,6,24808,f,"Oceanside, NY",Oceanside,New York,NY,All Residential,-1,358750.0,0.014851,-0.080128,424000.0,0.073431,0.214900,226.906552,-0.006505,-0.103888,229.744287,0.012868,0.070066,24.0,-0.076923,1.181818,9.0,0.125000,0.285714,18.0,-0.100000,0.285714,181.0,-0.071795,0.371212,7.5,0.0,-4.5,105.0,20.0,23.0,0.918497,-0.040737,-0.026696,0.041667,-0.035256,0.041667,0.138122,-0.036237,0.016909,0.111111,0.111111,-0.174603,"Nassau County, NY",35004,2024-01-14 14:20:58
11,2013-10-01,2013-10-31,30,place,6,37209,f,"Sterling, GA",Sterling,Georgia,GA,Single Family Residential,6,144900.0,1.281890,0.039455,199000.0,0.602254,0.425114,90.619137,1.025017,0.212372,115.362319,0.474633,0.373478,1.0,-0.666667,0.000000,NaN,NaN,NaN,1.0,-0.750000,-0.750000,19.0,-0.050000,0.461538,19.0,12.3,6.0,270.0,226.0,71.0,1.000000,0.059214,0.003574,0.000000,-0.333333,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,"Brunswick, GA",15260,2024-01-14 14:20:58
12,2018-03-01,2018-03-31,30,place,6,34655,f,"Riverview Park, PA",Riverview Park,Pennsylvania,PA,Single Family Residential,6,187500.0,0.250000,0.562500,219900.0,0.047642,0.100050,98.274541,-0.010736,-0.140957,83.753406,0.011395,-0.296928,2.0,-0.333333,0.000000,2.0,-0.333333,-0.333333,3.0,-0.400000,0.500000,8.0,0.142857,1.000000,4.0,1.7,2.0,51.0,39.0,-17.0,0.986381,-0.005267,0.072786,0.000000,-0.333333,0.000000,0.250000,-0.035714,-0.250000,0.500000,0.166667,-0.166667,"Reading, PA",39740,2024-01-14 14:20:58
13,2015-12-01,2015-12-31,30,place,6,33989,f,"Mechanicsville, MD",Mechanicsville,Maryland,MD,All Residential,-1,249000.0,-0.045977,-0.400000,229950.0,-0.099224,-0.148097,136.913428,0.064013,0.000155,119.270833,-0.195165,-0.178166,12.0,-0.368421,0.333333,10.0,0.250000,1.500000,17.0,0.416667,0.416667,75.0,-0.038462,0.071429,6.3,2.2,-1.5,40.0,-81.0,-42.0,0.978098,0.002253,-0.010008,0.166667,0.008772,-0.055556,0.133333,-0.058974,0.047619,0.500000,0.250000,0.000000,"California, MD",15680,2024-01-14 14:20:58
14,2020-03-01,2020-03-31,30,place,6,373,f,"Andover, MN",Andover,Minnesota,MN,Single Family Residential,6,350000.0,0.165889,0.155116,375000.0,0.000003,0.000000,138.512496,-0.050645,0.014520,146.076923,0.047633,0.076269,37.0,0.608696,0.193548,39.0,0.625000,0.114286,63.0,0.909091,0.400000,72.0,0.263158,0.043478,1.9,-0.6,-0.3,36.0,-2.0,-1.0,0.996594,0.000052,0.008570,0.216216,-0.218566,0.022668,0.166667,0.078947,0.007246,0.717949,0.342949,0.175092,"Minneapolis, MN",33460,2024-01-14 14:20:58
15,2013-06-01,2013-06-30,30,place,6,15595,f,"Rialto, CA",Rialto,California,CA,Multi-Family (2-4 Unit),4,167000.0,-0.542466,-0.469841,235000.0,0.022184,0.342857,122.076023,0.262902,0.819902,141.005203,-0.023585,0.200505,1.0,0.000000,0.000000,1.0,-0.500000,-0.666667,2.0,1.000000,-0.750000,4.0,0.000000,-0.600000,4.0,0.0,-6.0,45.0,39.0,29.0,1.012121,-0.061408,0.012121,1.000000,0.000000,1.000000,0.250000,NaN,NaN,0.000000,-0.500000,-0.666667,"Riverside, CA",40140,2024-01-14 14:20:58
16,2021-05-01,2021-05-31,30,place,6,19951,f,"Union Bridge, MD",Union Bridge,Maryland,MD,Single Family Residential,6,332420.0,0.546140,0.715716,325000.0,0.092621,-0.338692,169.002673,0.251255,0.245931,236.294896,0.611637,0.631509,4.0,0.000000,0.000000,8.0,1.666667,3.000000,8.0,0.333333,3.000000,4.0,0.000000,-0.333333,1.0,0.0,-0.5,49.0,34.0,-34.0,1.010174,0.017426,0.010320,0.250000,0.000000,0.000000,0.250000,-0.250000,-0.083333,0.750000,-0.250000,0.250000,"Baltimore, MD",12580,2024-01-14 14:20:58
17,2013-09-01,2013-09-30,30,place,6,30434,f,"Orwell, NY",Orwell,New York,NY,Single Family Residential,6,115000.0,-0.142060,NaN,NaN,NaN,NaN,103.046595,0.036293,NaN,NaN,NaN,NaN,1.0,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.0,0.000000,NaN,11.0,0.0,NaN,819.0,415.0,NaN,0.967199,0.067589,NaN,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Syracuse, NY",45060,2024-01-14 14:20:58
18,2022-02-01,2022-02-28,30,place,6,21075,f,"Youngstown, OH",Youngstown,Ohio,OH,Single Family Residential,6,76000.0,0.078014,0.394495,97250.0,0.092697,0.296667,57.062594,0.017795,0.423452,65.778502,-0.054516,0.108443,64.0,0.185185,0.560976,51.0,0.000000,0.186047,70.0,0.060606,-0.066667,124.0,0.024793,0.240000,1.9,-0.3,-0.5,42.0,-10.0,7.0,0.973758,0.025368,0.025446,0.484375,0.225116,0.313643,0.185484,0.003666,-0.004516,0.509804,0.098039,-0.164615,"Youngstown, OH",49660,2024-01-14 14:20:58
19,2014-04-01,2014-04-30,30,place,6,12918,f,"Nashua, NH",Nashua,New Hampshire,NH,Single Family Residential,6,237900.0,0.043421,0.027499,225900.0,0.023561,0.057584,131.573597,0.027508,0.020405,135.573883,0.090790,0.056204,42.0,0.076923,-0.142857,18.0,-0.280000,-0.333333,73.0,0.258621,0.013889,188.0,0.167702,0.044444,4.5,0.4,0.8,129.0,51.0,45.0,0.982499,-0.004447,-0.000669,0.261905,0.031136,-0.003401,NaN,NaN,NaN,0.111111,0.031111,0.111111,"Manchester, NH",31700,2024-01-14 14:20:58

In [5]:
# print numbers of columns and rows

print('Num of rows:', len(df))
print('Num of cols:', len(df.columns))

Num of rows: 5164217
Num of cols: 58

In [6]:
#data types by columns
df.dtypes

period_begin                       object
period_end                         object
period_duration                     int64
region_type                        object
region_type_id                      int64
table_id                            int64
is_seasonally_adjusted             object
region                             object
city                               object
state                              object
state_code                         object
property_type                      object
property_type_id                    int64
median_sale_price                 float64
median_sale_price_mom             float64
median_sale_price_yoy             float64
median_list_price                 float64
median_list_price_mom             float64
median_list_price_yoy             float64
median_ppsf                       float64
median_ppsf_mom                   float64
median_ppsf_yoy                   float64
median_list_ppsf                  float64
median_list_ppsf_mom              float64
median_list_ppsf_yoy              float64
homes_sold                        float64
homes_sold_mom                    float64
homes_sold_yoy                    float64
pending_sales                     float64
pending_sales_mom                 float64
pending_sales_yoy                 float64
new_listings                      float64
new_listings_mom                  float64
new_listings_yoy                  float64
inventory                         float64
inventory_mom                     float64
inventory_yoy                     float64
months_of_supply                  float64
months_of_supply_mom              float64
months_of_supply_yoy              float64
median_dom                        float64
median_dom_mom                    float64
median_dom_yoy                    float64
avg_sale_to_list                  float64
avg_sale_to_list_mom              float64
avg_sale_to_list_yoy              float64
sold_above_list                   float64
sold_above_list_mom               float64
sold_above_list_yoy               float64
price_drops                       float64
price_drops_mom                   float64
price_drops_yoy                   float64
off_market_in_two_weeks           float64
off_market_in_two_weeks_mom       float64
off_market_in_two_weeks_yoy       float64
parent_metro_region                object
parent_metro_region_metro_code      int64
last_updated                       object
dtype: object

In [7]:
#let's read the url path and read the csv
def lambda_handler(url):
  df = pd.read_csv(url, compression='gzip', sep='\t')

# now lets treat the data

In [8]:
# because we will later transform the data into a CSV file, the 'COMMA' would get in the way
#so let's see if there is any line with Comma
df_containing_comma = df[df['city'].str.contains(',')]

In [9]:
df_containing_comma.head()

,period_begin,period_end,period_duration,region_type,region_type_id,table_id,is_seasonally_adjusted,region,city,state,state_code,property_type,property_type_id,median_sale_price,median_sale_price_mom,median_sale_price_yoy,median_list_price,median_list_price_mom,median_list_price_yoy,median_ppsf,median_ppsf_mom,median_ppsf_yoy,median_list_ppsf,median_list_ppsf_mom,median_list_ppsf_yoy,homes_sold,homes_sold_mom,homes_sold_yoy,pending_sales,pending_sales_mom,pending_sales_yoy,new_listings,new_listings_mom,new_listings_yoy,inventory,inventory_mom,inventory_yoy,months_of_supply,months_of_supply_mom,months_of_supply_yoy,median_dom,median_dom_mom,median_dom_yoy,avg_sale_to_list,avg_sale_to_list_mom,avg_sale_to_list_yoy,sold_above_list,sold_above_list_mom,sold_above_list_yoy,price_drops,price_drops_mom,price_drops_yoy,off_market_in_two_weeks,off_market_in_two_weeks_mom,off_market_in_two_weeks_yoy,parent_metro_region,parent_metro_region_metro_code,last_updated
4653,2019-04-01,2019-04-30,30,place,6,36167,f,"Spencer, Ma, MA","Spencer, Ma",Massachusetts,MA,All Residential,-1,300000.0,0.290323,0.382488,299900.0,0.211962,0.200080,169.296117,0.083495,0.123415,150.966184,0.007157,-0.059032,11.0,0.000000,-0.083333,10.0,-0.090909,-0.090909,21.0,0.166667,0.105263,46.0,0.150000,0.277778,4.2,0.6,1.2,85.0,49.0,-17.0,0.969693,-0.007548,-0.005986,0.363636,0.181818,0.280303,0.304348,0.054348,0.109903,0.700000,0.063636,-0.118182,"Worcester, MA",49340,2024-01-14 14:20:58
8775,2023-02-01,2023-02-28,30,place,6,12839,f,"Washington, DC","Washington, DC",Columbia,DC,Single Family Residential,6,925000.0,0.089517,-0.191787,650000.0,0.007752,0.026856,402.173913,0.129181,-0.103680,504.057710,-0.018325,-0.043879,63.0,0.235294,-0.329787,64.0,0.306122,-0.189873,99.0,0.285714,-0.226562,238.0,0.012766,0.344633,3.8,-0.8,1.9,64.0,-1.0,45.0,0.966020,-0.000150,-0.069815,0.174603,-0.001867,-0.325397,0.247899,0.009601,0.112306,0.500000,0.051020,-0.183544,"Washington, DC",47894,2024-01-14 14:20:58
9267,2017-12-01,2017-12-31,30,place,6,36167,f,"Spencer, Ma, MA","Spencer, Ma",Massachusetts,MA,Single Family Residential,6,225000.0,-0.100000,0.046512,219000.0,-0.004545,0.200987,139.372376,0.126474,0.134277,137.847222,0.008593,-0.001013,10.0,-0.230769,-0.333333,3.0,-0.571429,-0.625000,8.0,-0.384615,0.000000,30.0,-0.032258,-0.268293,3.0,0.6,0.3,15.0,-6.0,-43.0,0.967038,-0.023006,-0.007093,0.300000,-0.007692,0.100000,0.266667,0.040860,0.022764,0.333333,-0.238095,0.083333,"Worcester, MA",49340,2024-01-14 14:20:58
9972,2012-10-01,2012-10-31,30,place,6,36167,f,"Spencer, Ma, MA","Spencer, Ma",Massachusetts,MA,Multi-Family (2-4 Unit),4,97500.0,0.298926,-0.093023,185450.0,0.124621,0.091203,46.866984,0.527115,0.070747,123.385417,0.206859,0.056704,2.0,-0.500000,-0.333333,1.0,0.000000,0.000000,1.0,-0.666667,-0.500000,9.0,-0.181818,-0.100000,4.5,1.7,1.2,70.0,-66.0,-30.0,0.847211,-0.052803,-0.031851,0.500000,0.250000,0.500000,0.444444,0.262626,-0.355556,0.000000,0.000000,0.000000,"Worcester, MA",49340,2024-01-14 14:20:58
14193,2019-09-01,2019-09-30,30,place,6,36167,f,"Spencer, Ma, MA","Spencer, Ma",Massachusetts,MA,Multi-Family (2-4 Unit),4,207450.0,-0.149795,0.142975,292400.0,0.170068,0.236364,86.165179,-0.239021,0.224353,161.973426,0.101860,0.064189,2.0,0.000000,-0.333333,1.0,-0.500000,-0.500000,2.0,-0.500000,0.000000,5.0,0.000000,-0.166667,2.5,0.0,0.5,60.0,48.0,50.0,1.026121,0.009030,0.040990,0.500000,-0.500000,-0.166667,0.200000,0.000000,-0.300000,0.000000,-0.500000,-1.000000,"Worcester, MA",49340,2024-01-14 14:20:58

In [10]:
# let's remove the commas from the city column
df['city'] = df['city'].str.replace(',','')

In [11]:
# Now let's leave only the necessary columns
cols = ['period_begin','period_end','period_duration', 'region_type', 'region_type_id', 'table_id',
    'is_seasonally_adjusted', 'city', 'state', 'state_code', 'property_type', 'property_type_id',
    'median_sale_price', 'median_list_price', 'median_ppsf', 'median_list_ppsf', 'homes_sold',
    'inventory', 'months_of_supply', 'median_dom', 'avg_sale_to_list', 'sold_above_list', 'parent_metro_region_metro_code',
    'last_updated']
df = df[cols]

In [12]:
# drop null values

df = df.dropna()

In [13]:
#let's change the period_begin and period_end to date time object and extract years and month.
df['period_begin'] = pd.to_datetime(df['period_begin'])
df['period_end'] = pd.to_datetime(df['period_end'])

df["period_begin_in_years"] = df['period_begin'].dt.year
df["period_end_in_years"] = df['period_end'].dt.year

df["period_begin_in_months"] = df['period_begin'].dt.month
df["period_end_in_months"] = df['period_end'].dt.month

In [14]:
#let's map the month number to their respective month name.
month_dict = {
    "period_begin_in_months": {
        1 : "Jan",
          2 :  "Feb",
          3: "Mar",
          4: "Apr",
          5: "May",
          6: "Jun",
          7: "Jul",
          8: "Aug",
          9: "Sep",
          10: "Oct",
          11: "Nov",
          12: "Dec",
    },

    "period_end_in_months": {
            1 : "Jan",
             2 :  "Feb",
             3: "Mar",
             4: "Apr",
             5: "May",
             6: "Jun",
             7: "Jul",
             8: "Aug",
             9: "Sep",
             10: "Oct",
             11: "Nov",
             12: "Dec"
        }}

In [15]:
df = df.replace(month_dict)
print('Num of rows:', len(df))
print('Num of cols:', len(df.columns))

Num of rows: 4076574
Num of cols: 28

In [16]:
df.head(20)

,period_begin,period_end,period_duration,region_type,region_type_id,table_id,is_seasonally_adjusted,city,state,state_code,property_type,property_type_id,median_sale_price,median_list_price,median_ppsf,median_list_ppsf,homes_sold,inventory,months_of_supply,median_dom,avg_sale_to_list,sold_above_list,parent_metro_region_metro_code,last_updated,period_begin_in_years,period_end_in_years,period_begin_in_months,period_end_in_months
1,2019-09-01,2019-09-30,30,place,6,26318,f,West Little River,Florida,FL,Single Family Residential,6,216000.0,264900.0,208.688245,207.384378,27.0,62.0,2.3,44.0,0.964801,0.185185,33124,2024-01-14 14:20:58,2019,2019,Sep,Sep
3,2022-11-01,2022-11-30,30,place,6,17859,f,South Fulton,Tennessee,TN,Single Family Residential,6,117500.0,136500.0,55.025320,72.327265,2.0,7.0,3.5,52.0,0.856925,0.000000,46460,2024-01-14 14:20:58,2022,2022,Nov,Nov
4,2014-09-01,2014-09-30,30,place,6,26490,f,Waggaman,Louisiana,LA,All Residential,-1,50000.0,55000.0,37.936267,46.230441,7.0,47.0,6.7,651.0,0.984588,0.142857,35380,2024-01-14 14:20:58,2014,2014,Sep,Sep
6,2013-01-01,2013-01-31,30,place,6,23508,f,Hurley,New York,NY,All Residential,-1,183500.0,166450.0,132.793227,102.674183,2.0,40.0,20.0,164.0,0.997421,0.500000,28740,2024-01-14 14:20:58,2013,2013,Jan,Jan
7,2017-11-01,2017-11-30,30,place,6,34777,f,Six Mile Run,New Jersey,NJ,Single Family Residential,6,450000.0,384950.0,192.967410,178.737907,1.0,9.0,9.0,20.0,1.002227,1.000000,35154,2024-01-14 14:20:58,2017,2017,Nov,Nov
8,2014-02-01,2014-02-28,30,place,6,20540,f,Westernport,Maryland,MD,Single Family Residential,6,50000.0,34900.0,39.304671,13.569207,2.0,15.0,7.5,40.0,0.862599,0.000000,19060,2024-01-14 14:20:58,2014,2014,Feb,Feb
9,2017-09-01,2017-09-30,30,place,6,12291,f,Neptune Beach,Florida,FL,Single Family Residential,6,495000.0,394950.0,155.562539,234.142875,1.0,23.0,23.0,212.0,0.960883,0.000000,27260,2024-01-14 14:20:58,2017,2017,Sep,Sep
10,2013-12-01,2013-12-31,30,place,6,24808,f,Oceanside,New York,NY,All Residential,-1,358750.0,424000.0,226.906552,229.744287,24.0,181.0,7.5,105.0,0.918497,0.041667,35004,2024-01-14 14:20:58,2013,2013,Dec,Dec
11,2013-10-01,2013-10-31,30,place,6,37209,f,Sterling,Georgia,GA,Single Family Residential,6,144900.0,199000.0,90.619137,115.362319,1.0,19.0,19.0,270.0,1.000000,0.000000,15260,2024-01-14 14:20:58,2013,2013,Oct,Oct
12,2018-03-01,2018-03-31,30,place,6,34655,f,Riverview Park,Pennsylvania,PA,Single Family Residential,6,187500.0,219900.0,98.274541,83.753406,2.0,8.0,4.0,51.0,0.986381,0.000000,39740,2024-01-14 14:20:58,2018,2018,Mar,Mar
13,2015-12-01,2015-12-31,30,place,6,33989,f,Mechanicsville,Maryland,MD,All Residential,-1,249000.0,229950.0,136.913428,119.270833,12.0,75.0,6.3,40.0,0.978098,0.166667,15680,2024-01-14 14:20:58,2015,2015,Dec,Dec
14,2020-03-01,2020-03-31,30,place,6,373,f,Andover,Minnesota,MN,Single Family Residential,6,350000.0,375000.0,138.512496,146.076923,37.0,72.0,1.9,36.0,0.996594,0.216216,33460,2024-01-14 14:20:58,2020,2020,Mar,Mar
15,2013-06-01,2013-06-30,30,place,6,15595,f,Rialto,California,CA,Multi-Family (2-4 Unit),4,167000.0,235000.0,122.076023,141.005203,1.0,4.0,4.0,45.0,1.012121,1.000000,40140,2024-01-14 14:20:58,2013,2013,Jun,Jun
16,2021-05-01,2021-05-31,30,place,6,19951,f,Union Bridge,Maryland,MD,Single Family Residential,6,332420.0,325000.0,169.002673,236.294896,4.0,4.0,1.0,49.0,1.010174,0.250000,12580,2024-01-14 14:20:58,2021,2021,May,May
18,2022-02-01,2022-02-28,30,place,6,21075,f,Youngstown,Ohio,OH,Single Family Residential,6,76000.0,97250.0,57.062594,65.778502,64.0,124.0,1.9,42.0,0.973758,0.484375,49660,2024-01-14 14:20:58,2022,2022,Feb,Feb
19,2014-04-01,2014-04-30,30,place,6,12918,f,Nashua,New Hampshire,NH,Single Family Residential,6,237900.0,225900.0,131.573597,135.573883,42.0,188.0,4.5,129.0,0.982499,0.261905,31700,2024-01-14 14:20:58,2014,2014,Apr,Apr
20,2017-09-01,2017-09-30,30,place,6,23166,f,Guerneville,California,CA,Single Family Residential,6,426000.0,449000.0,407.155420,383.136344,8.0,27.0,3.4,43.0,1.020971,0.625000,42220,2024-01-14 14:20:58,2017,2017,Sep,Sep
21,2015-03-01,2015-03-31,30,place,6,23045,f,Franconia,Virginia,VA,Townhouse,13,329000.0,399950.0,259.664325,260.515904,12.0,22.0,1.8,7.0,0.976106,0.083333,47894,2024-01-14 14:20:58,2015,2015,Mar,Mar
22,2018-04-01,2018-04-30,30,place,6,36630,f,Salem Lakes,Wisconsin,WI,All Residential,-1,182000.0,272400.0,118.623233,138.469856,29.0,65.0,2.2,56.0,0.995399,0.275862,29404,2024-01-14 14:20:58,2018,2018,Apr,Apr
23,2023-03-01,2023-03-31,30,place,6,35753,f,Appleton,Wisconsin,WI,Multi-Family (2-4 Unit),4,240000.0,247450.0,138.546798,146.361884,3.0,6.0,2.0,42.0,1.024844,0.666667,11540,2024-01-14 14:20:58,2023,2023,Mar,Mar

In [ ]:
file_name = 'File_Name.csv'

df.to_csv(file_name, index=False)